name: Build/release

on: 
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build_macos:
    name: MacOS build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: 1.56.1
      # - name: Prepare cache directory
      #   run: mkdir ./resources/temp
      # - uses: Swatinem/rust-cache@v1
      #   with:
      #     working-directory: ./resources/temp/holochain
      - name: Install depedencies
        env:
          LDFLAGS: "-L/usr/local/opt/openssl/lib"
          CPPFLAGS: "-I/usr/local/opt/openssl/include"
          PKG_CONFIG_PATH: "/usr/local/opt/openssl/lib/pkgconfig"
        run: |
          brew install libsodium openssl
          rustup target add wasm32-unknown-unknown
      - name: Build Holochain
        env:
          SQLCIPHER_STATIC: 1
          LDFLAGS: "-L/usr/local/opt/openssl/lib"
          CPPFLAGS: "-I/usr/local/opt/openssl/include"
          PKG_CONFIG_PATH: "/usr/local/opt/openssl/lib/pkgconfig"
        run: |
          cargo install lair_keystore --git https://github.com/guillemcordoba/lair --rev 8c0a3683d93540301af53688ea431c7cc0beb438
          cargo install --locked holochain --git https://github.com/holochain/holochain.git --tag holochain-0.0.123
          cargo install holochain_cli --version 0.0.24
          ./scripts/copy-hc.sh
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Node.js, NPM & Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
      - name: Retrieve tag version
        id: ref
        run: |
          pkgver=$(node ./scripts/get-pkg-version.js)
          echo ::set-output name=version::$pkgver
      - name: Install deps
        run: npm i --legacy-peer-deps
      - name: Build languages
        run: npm run get-languages
      - name: setup for codesigning (macos only)
        uses:  figleafteam/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.COMMUNITIES_APPLE_CERT }}
          p12-password: ${{ secrets.COMMUNITIES_APPLE_CERT_PASSWORD }}
      - name: Build app
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.github_token }}
          APPLE_DEV_IDENTITY: ${{ secrets.APPLE_DEV_IDENTITY }}
          APPLE_ID_EMAIL: ${{ secrets.APPLE_ID_EMAIL }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          DEBUG: electron-osx-sign*,electron-notarize*
      - name: Cache macOS release (x64)
        uses: actions/upload-artifact@v1
        with:
          name: Flux-${{steps.ref.outputs.version}}.dmg
          path: ./dist_electron/Flux-${{steps.ref.outputs.version}}.dmg
      - name: Cache latest-mac.yml
        uses: actions/upload-artifact@v1
        with:
          name: latest-mac.yml
          path: ./dist_electron/latest-mac.yml

  # build_windows:
  #   name: Windows build
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: 1.55.0
  #     - uses: Swatinem/rust-cache@v1
  #       with:
  #         working-directory: ./resources/temp/holochain
  #     - name: Build Holochain
  #       env:
  #         SQLCIPHER_STATIC: 1
  #       run: |
  #         rustup target add wasm32-unknown-unknown
  #         cargo install lair_keystore --git https://github.com/holochain/lair --rev bd92b76ad9cc18bc0c0db215e4bea9767c9003cf
  #         cargo install holochain --git https://github.com/holochain/holochain --rev af7de6eca55d8dd3d22bbfccee738fd11f2a2e12
  #         cargo install holochain_cli --git https://github.com/holochain/holochain --rev af7de6eca55d8dd3d22bbfccee738fd11f2a2e12
  #         ./scripts/copy-hc.sh
  #     - name: Install Node.js, NPM & Yarn
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 16.13.0
  #     - name: Retrieve tag version
  #       id: ref
  #       run: echo "::set-output name=version::$(node ./scripts/get-pkg-version.js)"
  #     - name: Install deps
  #       run: npm i --legacy-peer-deps
  #     - name: Build languages
  #       run: npm run get-languages
  #     - name: Build app
  #       run: npm run release
  #       env:
  #         GH_TOKEN: ${{ secrets.github_token }}
  #     - name: Cache nsis release
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: Flux Setup ${{steps.ref.outputs.version}}.exe
  #         path: ./dist_electron/Flux Setup ${{steps.ref.outputs.version}}.exe
  #     - name: Cache latest-windows.yml
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: latest-windows.yml
  #         path: ./dist_electron/latest.yml

  build_linux:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: 1.56.1
      # - name: Prepare cache directory
      #   run: mkdir ./resources/temp/holochain
      # - uses: Swatinem/rust-cache@v1
      #   with:
      #     working-directory: ./resources/temp/holochain
      - name: Install depedencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libsqlcipher-dev
          rustup target add wasm32-unknown-unknown
      - name: Build Holochain
        env:
          SQLCIPHER_STATIC: 1
        run: |
          cargo install lair_keystore --git https://github.com/guillemcordoba/lair --rev 8c0a3683d93540301af53688ea431c7cc0beb438
          cargo install --locked holochain --git https://github.com/holochain/holochain.git --tag holochain-0.0.123
          cargo install holochain_cli --version 0.0.24
          ./scripts/copy-hc.sh
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Node.js, NPM & Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
      - name: Retrieve tag version
        id: ref
        run: |
          pkgver=$(node ./scripts/get-pkg-version.js)
          echo ::set-output name=version::$pkgver
      - name: Install deps
        run: npm i --legacy-peer-deps
      - name: Build languages
        run: npm run get-languages
      - name: Build app
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.github_token }}
      - name: Cache AppImage
        uses: actions/upload-artifact@v1
        with:
          name: Flux-${{steps.ref.outputs.version}}.AppImage
          path: ./dist_electron/Flux-${{steps.ref.outputs.version}}.AppImage
      - name: Cache .deb release (x64)
        uses: actions/upload-artifact@v1
        with:
          name: flux_${{steps.ref.outputs.version}}_amd64.deb
          path: ./dist_electron/flux_${{steps.ref.outputs.version}}_amd64.deb
      - name: Cache snap release (x64)
        uses: actions/upload-artifact@v1
        with:
          name: flux_${{steps.ref.outputs.version}}_amd64.snap
          path: ./dist_electron/flux_${{steps.ref.outputs.version}}_amd64.snap
      - name: Cache latest-linux.yml
        uses: actions/upload-artifact@v1
        with:
          name: latest-linux.yml
          path: ./dist_electron/latest-linux.yml

  prepare_release:
    name: Prepare release draft
    needs: [build_linux, build_macos]
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Node.js, NPM & Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
      - name: Retrieve tag version
        id: ref
        run: |
          pkgver=$(node ./scripts/get-pkg-version.js)
          echo ::set-output name=version::$pkgver
      - name: Download AppImage
        uses: actions/download-artifact@v1
        with:
          name: Flux-${{steps.ref.outputs.version}}.AppImage
          path: .
      - name: Download deb
        uses: actions/download-artifact@v1
        with:
          name: flux_${{steps.ref.outputs.version}}_amd64.deb
          path: .
      - name: Download snap
        uses: actions/download-artifact@v1
        with:
          name: flux_${{steps.ref.outputs.version}}_amd64.snap
          path: .
      - name: Download macOS image
        uses: actions/download-artifact@v1
        with:
          name: Flux-${{steps.ref.outputs.version}}.dmg
          path: .
      # - name: Download Windows Exe
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: Flux Setup ${{steps.ref.outputs.version}}.exe
      #     path: .
      # - name: Download latest-windows.yml
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: latest-windows.yml
      #     path: .
      - name: Download latest-linux.yml
        uses: actions/download-artifact@v1
        with:
          name: latest-linux.yml
          path: .
      - name: Download latest-mac.yml
        uses: actions/download-artifact@v1
        with:
          name: latest-mac.yml
          path: .
      - name: Generate SHA256 checksums
        run: |
          sha256sum "Flux-${{steps.ref.outputs.version}}.AppImage" >> "SHA256SUMS.txt"
          sha256sum "flux_${{steps.ref.outputs.version}}_amd64.deb" >> "SHA256SUMS.txt"
          sha256sum "Flux-${{steps.ref.outputs.version}}.dmg" >> "SHA256SUMS.txt"
          sha256sum "flux_${{steps.ref.outputs.version}}_amd64.snap" >> "SHA256SUMS.txt"
          sha256sum "latest-linux.yml" >> "SHA256SUMS.txt"
          sha256sum "latest-mac.yml" >> "SHA256SUMS.txt"
      - name: Verify checksums
        run: sha256sum -c SHA256SUMS.txt
      - name: Create a new release draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: v${{steps.ref.outputs.version}}
          release_name: Release v${{steps.ref.outputs.version}} 
          body: If you can read this, we have forgotten to fill in the changelog. Sorry!
          draft: true 
      - name: Upload .deb installer (x64)
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./flux_${{steps.ref.outputs.version}}_amd64.deb
          asset_name: flux_${{steps.ref.outputs.version}}_amd64.deb
          asset_content_type: application/octet-stream
      - name: Upload AppImage binary (arm64)
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Flux-${{steps.ref.outputs.version}}.AppImage
          asset_name: Flux-${{steps.ref.outputs.version}}.AppImage
          asset_content_type: application/octet-stream
      - name: Upload Snap binary (arm64)
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./flux_${{steps.ref.outputs.version}}_amd64.snap
          asset_name: flux_${{steps.ref.outputs.version}}_amd64.snap
          asset_content_type: application/octet-stream
      - name: Upload macOS image
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Flux-${{steps.ref.outputs.version}}.dmg
          asset_name: Flux-${{steps.ref.outputs.version}}.dmg
          asset_content_type: application/octet-stream
      # - name: Upload Windows exe
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./Flux Setup ${{steps.ref.outputs.version}}.exe
      #     asset_name: Flux Setup ${{steps.ref.outputs.version}}.exe
      #     asset_content_type: application/octet-stream
      - name: Upload latest-linux.yml
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./latest-linux.yml
          asset_name: latest-linux.yml
          asset_content_type: application/octet-stream
      - name: Upload latest-mac.yml
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./latest-mac.yml
          asset_name: latest-mac.yml
          asset_content_type: application/octet-stream
      # - name: Upload latest-windows.yml
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.github_token }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./latest.yml
      #     asset_name: latest.yml
      #     asset_content_type: application/octet-stream
      - name: Upload the checksums
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./SHA256SUMS.txt
          asset_name: SHA256SUMS.txt
          asset_content_type: text/plain

