name: Tests

on:
  push:
  pull_request:
    branches:
      - 'test/setup'
      # - '*'
      # - '*/*'
      # - '**'
      # - '!master'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js, NPM & Yarn
      uses: actions/setup-node@v2
      with:
        node-version: 16.14.0
    - name: Install modules
      run: yarn install
    - name: Run lint
      run: yarn run lint
    - name: Run tests
      run: yarn run test